### ISSUE TITLE
Printing?

### ISSUE THREAD

**Issue by hsarji** [alangrainger/obsidian-share#1]
Your script is wonderful. I ran into an issue when trying to print your sample page from my iPad. I tried different ways to print (including exporting to PDF Expert).

**Comment by alangrainger** [comment]
Can you please post this on the forum thread so it can benefit all users? I will disable the Issues section here on Github.

https://forum.obsidian.md/t/obsidian-share-publicly-share-notes-without-needing-a-full-digital-garden-supports-themes-images-callouts-and-more/42788

**Comment by MicaelJarniac** [comment]
Did you find a solution there?

**Comment by alangrainger** [comment]
Strange, I don't know why this was closed, but I'll merge it into #75 which is the same issue.
