### ISSUE TITLE
[FR] Gif and webm support

### ISSUE THREAD

**Issue by FeralFlora** [alangrainger/obsidian-share#13]
I just ran into this message:

![image](https://github.com/alangrainger/obsidian-share/assets/33608083/4941c4dc-3505-410f-926b-77af5f2232c3)

I would be great to be able to embed gifs and / or webm into notes, especially for demonstration purposes in guides and such.

**Comment by alangrainger** [comment]
I have added these now. Please be aware there is a limit of 1MB for filesize. Anything over that you should host with Imgur or other hosting and then link the file back.

https://file.obsidianshare.com/61/960213442bfaef4746326139236c6964.html

**Comment by FeralFlora** [comment]
> I have added these now.

Great, thank you very much! I will mind the file size limit, and thanks for the workaround

**Comment by FeralFlora** [comment]
Nevermind, sorry, I had one above 1 Mb that I hadn't noticed!

**Comment by FeralFlora** [comment]
@alangrainger WebM is not working for me. The attachment online refers to my local storage as the path.

**Comment by alangrainger** [comment]
Please create a demo vault with the plugins/themes needed to make this issue occur.

Once you've created the demo vault, zip it up and upload as an attachment in this thread.

Thanks!

**Comment by alangrainger** [comment]
Sorry - working on automatic issue rules 😬 

I didn't realise WebM was so different. I will remove support for those for now (sorry!), and recommend that you host on a third-party service and link back, like you would for any video.

**Comment by alangrainger** [comment]
@FeralFlora .webm support is added in 0.5.11.
