### ISSUE TITLE
Bug when sharing a note

### ISSUE THREAD

**Issue by MelodyDuplaix** [alangrainger/obsidian-share#14]
I use the code styler plugin to give titles and style my codeblocks with this syntax:
````
```python title:name
code
```
````
Notes containing this syntax cannot be shared. The pop-up at the start of the sharing process appears, but then nothing happens and the link isn’t updated.

**Comment by alangrainger** [comment]
Please upload a zip of a demo vault which exhibits this issue, and I will sort it out.

**Comment by MelodyDuplaix** [comment]
I am very sorry, In the end, I couldn't figure out where it was coming from. I finally failed to recreate the bug with a test vault, but I still haven't managed to share my note on my chest.
I use a lot of snippets and plugins, so I'm going to try disabling them one by one to see where it might be coming from.

**Comment by alangrainger** [comment]
Make sure to run the BRAT command to update your Share Note plugin, just in case. You should be on version 0.3.14.

**Comment by MelodyDuplaix** [comment]
Okay, this is really strange. Even after deactivating all css and plugins, and uninstalling-reinstalling obsidian share with brat, the note still doesn't share in my main vault. The other notes are well shared, and this note is well shared in a test box.
Just in case, here is my note:
[Test.md](https://github.com/alangrainger/obsidian-share/files/12738486/Test.md)

**Comment by alangrainger** [comment]
Close and reopen Obsidian after updating the plugin? Only other thing I can think of....

**Comment by MelodyDuplaix** [comment]
I've tried that too, but still no change.
However, I've just tried to remove this line, and without this, the note is finally shared in my main vault too.:
```
#### 1.7.2) Avec la bibliothèque <span data-comment="What the form">WTF</span>
```
So I still haven't found the real reason, but I'll be able to share my note in the end.

**Comment by MelodyDuplaix** [comment]
However, I now have a strange behavior. When reinstalling obsidian share, the css snippets I use are no longer taken into account for note sharing, even though they've been reactivated.

**Comment by alangrainger** [comment]
Please do the troubleshooting steps here first to see if that resolves your problem:

https://github.com/alangrainger/obsidian-share#troubleshooting

**Comment by MelodyDuplaix** [comment]
No, I've tried several times, but the snippets are still not taken into account.

**Comment by alangrainger** [comment]
I'll close this for now - if you want to upload a demo vault which exhibits the issue then I can look into it for you.

**Comment by MelodyDuplaix** [comment]
It's really strange but I'd given up for the moment. I tried again after the last update and miraculously, everything was working properly again. So I don't know what happened, but everything's fine.
