### ISSUE TITLE
Add command to delete shared note

### ISSUE THREAD

**Issue by kometenstaub** [alangrainger/obsidian-share#15]
I did not find a way to delete a previously shared note (and optionally its associated data).

Would it be possible to add this?

**Comment by kometenstaub** [comment]
Btw, your FR template uses the `bug` label: https://github.com/alangrainger/obsidian-share/blob/main/.github/ISSUE_TEMPLATE/feature_request.md

**Comment by alangrainger** [comment]
Yes, deletion and also an admin page to manage all your notes in one place will be added in the future 👍 

> Btw, your FR template uses the bug label:

Thanks! Fixed up now.

**Comment by kometenstaub** [comment]
> Yes, deletion and also an admin page to manage all your notes in one place will be added in the future 👍

Thank you!

**Comment by FeralFlora** [comment]
> Yes, deletion and also an admin page to manage all your notes in one place will be added in the future 👍

If it's possible, it would be awesome if this admin page could include basic analytics like total unique visitors.

**Comment by alangrainger** [comment]
I've moved this feature request to the new "Feature and roadmap voting area":

https://github.com/alangrainger/obsidian-share/discussions/27

**Comment by alangrainger** [comment]
@kometenstaub @FeralFlora deleting notes has been added in 0.6.0:

Click the 🗑️ icon next to the shared link to delete, or use the `Delete note` command from the command palette:

<img src="https://github.com/alangrainger/obsidian-share/assets/16197738/ec22623f-3d75-4f9d-9eca-51f73d3eb061" width="320">

**Comment by FeralFlora** [comment]
> Click the 🗑️ icon next to the shared link to delete, or use the `Delete note` command from the command palette:
> <img alt="" width="320" src="https://user-images.githubusercontent.com/16197738/276636567-ec22623f-3d75-4f9d-9eca-51f73d3eb061.png">

These property buttons are very cool, didn't know you could do that and haven't seen anyone doing something like this yet
