### ISSUE TITLE
Only part of the note is uploaded

### ISSUE THREAD

**Issue by FeralFlora** [alangrainger/obsidian-share#19]
Sorry, no feature request this time, only bug reports.

When I upload [this note](https://github.com/alangrainger/obsidian-share/files/12840553/Zotero.Kanban.Reading.List.guide.-.Workflow.and.Setup.Guide.md) using **Force re-upload of all all data for this note**, less than half of it is uploaded, as you can see [here.](https://share.note.sx/e612da498b038c3e5e367043782e2b59)

I've followed the troubleshooting steps, and I've forced a reload without cache in both Firefox (ctrl + F5) and Vivaldi (developer tools), to no avail.

**Comment by alangrainger** [comment]
That's very strange. It works fine when I try it:

https://share.note.sx/67i6tydt

Maybe we can do the demo vault thing again - figure out a way to replicate it?

**Comment by alangrainger** [comment]
There isn't anything "wrong" exactly, the problem is that your CSS is 2.8 MB, which is fairly ridiculous for a CSS file. I'm not sure why my device is able to successfully upload that and yours isn't - I can only suggest to try again?

However, the reason the size is so large is I assume that there are a bunch of embedded assets which my plugin isn't picking up and extracting. I'll get that sorted out regardless.

In the meantime, please try upgrading to 0.5.4 and see if that helps, as I've made some improvements to the upload function.

**Comment by FeralFlora** [comment]
> Maybe we can do the demo vault thing again - figure out a way to replicate it?

I think the vault I just shared in https://github.com/alangrainger/obsidian-share/issues/20 can be regarded as a demo vault for this issue too.

> There isn't anything "wrong" exactly, the problem is that your CSS is 2.8 MB, which is fairly ridiculous for a CSS file. I'm not sure why my device is able to successfully upload that and yours isn't.

Hmm, I see. Can you clarify how the CSS size causes the incomplete upload issue?

> However, the reason the size is so large is I assume that there are a bunch of embedded assets which my plugin isn't picking up and extracting. I'll get that sorted out regardless.

Which types of assets might that be?

> In the meantime, please try upgrading to 0.5.4 and see if that helps, as I've made some improvements to the upload function.

I've tried to force re-upload using version 0.5.4, and I get a bit more uploaded, but not everything. Now, it consistently cuts off right after the "Recommended Kanban board settings" heading, so still quite a bit missing. [See here.](https://share.note.sx/e612da498b038c3e5e367043782e2b59)

**Comment by alangrainger** [comment]
> I think the vault I just shared in https://github.com/alangrainger/obsidian-share/issues/20 can be regarded as a demo vault for this issue too.

That works for me without issues though - https://share.note.sx/5d4d9v65 - no cutoffs.

**Comment by alangrainger** [comment]
> Now, it consistently cuts off right after the "Recommended Kanban board settings" heading, so still quite a bit missing. [See here.](https://share.note.sx/e612da498b038c3e5e367043782e2b59)

Can I just clarify what you mean here? I don't see any cutoff on that linked page - I see the linked/unlinked mentions at the end and everything looks great. Same URL:

![image](https://github.com/alangrainger/obsidian-share/assets/16197738/ffb8c838-9e37-44b0-8cda-676fc4a91341)

**Comment by FeralFlora** [comment]
> I don't see any cutoff on that linked page

That's very strange. This is how it looks to me after `ctrl + F5` refreshing on Firefox:
![image](https://github.com/alangrainger/obsidian-share/assets/33608083/e58a3c9c-056e-445b-b58e-c2ff69cf3d98)

**Comment by FeralFlora** [comment]
And it's the same in Vivaldi for me too.

**Comment by FeralFlora** [comment]
@alangrainger Maybe you have a cached version?

**Comment by alangrainger** [comment]
I've just tried it on my mobile device on its data connection, and it looks perfect. So that has removed any device and router cache from what I'm seeing, since I've not used that device previously.

Perhaps it's cached at your router? Can you try a mobile device on a mobile data connection, in an Incognito / Private Browsing tab?

**Comment by FeralFlora** [comment]
> Perhaps it's cached at your router? Can you try a mobile device on a mobile data connection, in an Incognito / Private Browsing tab?

That must have been it! I opened it on my phone with 
Wifi on: Cut off.
Wifi off: All there!

**Comment by alangrainger** [comment]
Brilliant! That's sadly going to make it a bit annoying for you to check what is actually published when you do updates 😞 

Maybe you can figure out a way to get your router to clear its cache. You did try a force refresh by Ctrl-clicking the refresh button in your browesr?

**Comment by FeralFlora** [comment]
> Brilliant! That's sadly going to make it a bit annoying for you to check what is actually published when you do updates 😞

Yes, that was my first thought, but I have a very accessible router, so I will see what I can do about it. Shouldn't be too difficult 👍

**Comment by FeralFlora** [comment]
> ![image](https://user-images.githubusercontent.com/16197738/273471421-e0c7f037-64bd-4265-807c-a489e5465e7b.png)

@alangrainger As you can see in your screenshots here, there is still an issue with missing callout icons. Should I open an issue on that?

**Comment by alangrainger** [comment]
By the way, on a completely unrelated note, you can significantly reduce the size of gifs by lowering the frame rate.

I noticed your main gif on that page has quite a high framerate, which means you're storing image after image inside the gif which doesn't need to be there.

Have a look at the one I made for my photos plugin here:

https://github.com/alangrainger/obsidian-google-photos/raw/main/img/demo.gif

It's huge in dimensions, and also includes full-colour photographs, which of course take up a lot of space. By reducing the framerate, that gif comes in at around 300kb. I did it with Photoshop - I'm not much of an expert so don't really know what tools can be used for that.

> Should I open an issue on that?

Yes please, that would be great thanks.

**Comment by FeralFlora** [comment]
> I'm not much of an expert so don't really know what tools can be used for that.

Thanks for the tip! I'm using ShareX to record, which has a framerate setting, so I can just change it there. It's currently set to 15 fps. I don't know how low is a good compromise, though.

![image](https://github.com/alangrainger/obsidian-share/assets/33608083/3fccfb0f-8790-4e38-9408-841c294fba1e)

**Comment by alangrainger** [comment]
5 frames per second would be ample for a tutorial gif I would imagine. Test it and see if it still looks fine.

**Comment by FeralFlora** [comment]
> 5 frames per second would be ample for a tutorial gif I would imagine. Test it and see if it still looks fine.

I will! Also, webm gives great results using less space, and allows users to pause. I tried to embed a webm file I uploaded to imgur, but I couldn't get it to work. How would you embed such a file?

Btw, this issue can be closed, right?

**Comment by MelodyDuplaix** [comment]
I didn't quite understand the solution. I have the same problem from time to time. The page is still displayed with the old version in my browser, even though it has been updated, which I was able to check by opening it in private browsing. I've tried changing the browser settings so that the https://share.note.sx/ cookies aren't stored, but that hasn't really changed anything. What was the solution in the end?

**Comment by FeralFlora** [comment]
> > Brilliant! That's sadly going to make it a bit annoying for you to check what is actually published when you do updates 😞
> 
> Yes, that was my first thought, but I have a very accessible router, so I will see what I can do about it. Shouldn't be too difficult 👍

@alangrainger I've taken a look at my router, and after clearing the DNS resolver's (knot resolver) cache, I still get the same cut-off version of the note. Could Rebind protection be part of the picture?

![image](https://github.com/alangrainger/obsidian-share/assets/33608083/66cbca7a-2a06-4873-b133-b5033c463d47)

**Comment by alangrainger** [comment]
@FeralFlora questions like embedding a webm into Obsidian are a bit outside the scope for this plugin's issue board, however paste this:

```
<video autoplay loop muted="true" poster="https://i.imgur.com/iHzu04nh.jpg">
    <source src="https://i.imgur.com/iHzu04n.mp4" type="video/mp4">
    <source src="https://i.imgur.com/iHzu04n.webm" type="video/webm">
</video>
```

Re the router, sorry, I don't know much about networking so won't be much help here.

Yes I think this issue can be closed now 👍 

@MelodyDuplaix 

If it's working in Private browsing, then it means it's just cached in your normal browser, so that's a different issue. Try Ctrl+clicking the refresh button to force a refresh of your browser.

**Comment by FeralFlora** [comment]
> Questions like embedding a webm into Obsidian are a bit outside the scope for this plugin's issue board

Right. Thanks a lot for the examples anyway!

**Comment by FeralFlora** [comment]
@alangrainger After trying to clear what I can on my router, without success, I think this is actually a Cloudflare issue.

I inspected the network tab when loading the note, and these are the response headers from Cloudflare:

![Uploading image.png…]()

`cf-cache-status: HIT` which means:
> Your resource was found in Cloudflare’s cache. This means that it has been previously accessed from your original server and loaded into Cache. It has all not expired.

And `cache-control | max-age=2678400`. This is [in seconds.](https://developers.cloudflare.com/cache/concepts/cache-control/)

2678400 seconds = 44640 hours = 1860 days.

So the cache lasts a very long time before it expires.

**Comment by alangrainger** [comment]
Yes, that's intentional. I cache for a year, but on every file upload (including CSS/JPG/asset URLs) it purges the cache for that URL.

The purge is working fine, but perhaps it takes Cloudflare a while to clear out the cache across its network?

**Comment by alangrainger** [comment]
> After trying to clear what I can on my router, without success, I think this is actually a Cloudflare issue.

Actually you can tell it's not a Cloudflare issue, since it works on your mobile device on data connection.

Your router is respecting the cache headers, and you need to force clear them from your router.

What I'll do is lower the browser cache time (your router in this case) to 4 hours (the standard), so after 4 hours your router will drop its local cache and fetch again from Cloudflare (which will have the new copy since its cache was purged).

**Comment by FeralFlora** [comment]
> Yes, that's intentional. I cache for a year

If you cache for a year, then why is the `max-age` 1860 days = 5 years in this instance?

> It's not the DNS cache, it's the web cache.

I'm pretty sure routers don't have web-caches, and that the router is not the issue.

Perhaps your server isn't following best practices for cache configuration, for example [by caching the HTML file](https://medium.com/pixelpoint/best-practices-for-cache-control-settings-for-your-website-ff262b38c5a2):
> The tricky part of the above technique is that you cannot forget about your html files; if you apply that setting to those too, you will never get new links for your css, js, or image files until you force a reload.
> **I recommend you apply Cache-Control: no-cache to html files.** Applying “no-cache” does not mean that there is no cache at all, it simply tells the browser to validate resources on the server before use it from the cache.

I'm not saying that this quote/source is the end-all be-all of cache best practices, but this recommendation is [echoed many places.](https://fred-gu.medium.com/fix-the-annoying-web-page-caching-issue-permanently-5d16527d0b5a)

I think this should be a high priority issue, because it is severely limiting the user-experience of Share note.

**Comment by alangrainger** [comment]
I can't do that, or it would cost me $$$$$$ to serve that much data without caching 😉 

You can tell it's a cache related to your computer/router/ISP, because you didn't get the same result when using your data connection. It could just as easily be cached at your internet provider.

**Comment by alangrainger** [comment]
I get this in my browser:

![image](https://github.com/alangrainger/obsidian-share/assets/16197738/ae7a42a4-4eb6-4586-b628-c0b1644fbf85)

Perhaps your ISP is adding heavy caching?

**Comment by FeralFlora** [comment]
> I can't do that, or it would cost me $$$$$$ to serve that much data without caching 😉

That's not how `no-cache` works though. It doesn't mean it will re-fetch from the server every time:

See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

> no-cache

> The no-cache response directive indicates that the response can be stored in caches, but the response must be validated with the origin server before each reuse, even when the cache is disconnected from the origin server.

> If you want caches to always check for content updates **while reusing stored content**, no-cache is the directive to use. It does this by requiring caches to revalidate each request with the origin server.

> **Note that no-cache does not mean "don't cache". no-cache allows caches to store a response but requires them to revalidate it before reuse. If the sense of "don't cache" that you want is actually "don't store", then no-store is the directive to use.**

**Comment by alangrainger** [comment]
> the response must be validated with the origin server before each reuse

This is the part I don't want. I can't have that much validation traffic.

As above, it's something in your path to the server. I suggest tethering your laptop to a mobile data connection and testing that way.

In case you missed it, here's what I see for your notes in my browser, which is the correct headers I expect to be sending:

![image](https://github.com/alangrainger/obsidian-share/assets/16197738/e2fdf8fd-19d1-4e4e-b6c4-1d059f22bba5)

**Comment by alangrainger** [comment]
> 2678400 seconds = 44640 hours = 1860 days.

Also you might want to check the math:

![image](https://github.com/alangrainger/obsidian-share/assets/16197738/297a7637-315f-4717-a7dc-1f7456465683)

**Comment by FeralFlora** [comment]
> > 2678400 seconds = 44640 hours = 1860 days.
> 
> Also you might want to check the math:

Oh shit, I forgot one divide by 60 🤦‍♂️

**Comment by FeralFlora** [comment]
> This is the part I don't want. I can't have that much validation traffic.

Why do you think this will cost you? By default, [Cloudflare doesn't cache html content](https://developers.cloudflare.com/cache/concepts/default-cache-behavior/):
> The Cloudflare CDN does not cache HTML by default.

**Comment by alangrainger** [comment]
FYI the link above regarding HTML files is referring to reactive apps that load Javascript assets:

> we use a technique implemented by many assets builders tools, like Webpack or Gulp. Each file will be precompiled on the server and hash sums are added to the file names, such as “app-72420c47cc.css”

In that case the content is in the Webpack bundle, and yes it's smart to have the HTML file no-cache for a reactive website so that the latest bundles load.

**Comment by alangrainger** [comment]
> Why do you think this will cost you? By default, [Cloudflare doesn't cache html content](https://developers.cloudflare.com/cache/concepts/default-cache-behavior/):

Please, I would appreciate to stop this conversation. I don't need the arguing.

Serving data costs money. Using Cloudflare to cache the data saves money. Cloudflare can be requested to cache HTML, and I have done so.

Please, enough.

**Comment by FeralFlora** [comment]
> I expect to be sending

Not arguing anything, just a clarifying question: Does this mean that a 4-hour CDN cache refresh delay when updating notes (without uploading new files) is the intended behavior?

**Comment by alangrainger** [comment]
> Does this mean that a 4-hour CDN cache refresh delay when updating notes (without uploading new files) is the intended behavior?

No. The CDN is cleared **immediately** when you upload a note.

The **only** caching is on your device, or your router, or your ISP. It is not anywhere in the Share Note system.

Performing a Ctrl+click refresh in my browser **always** returns the updated copy. If you are seeing different results it is something your local network, nothing to do with Cloudflare, the CDN, or the Share Note server. You need to ask your local device to fetch from the CDN.

You can verify this by loading from a different device on a different data connection, as you previously did with your wifi on / wifi off test.

**Comment by FeralFlora** [comment]
> You can verify this by loading from a different device on a different data connection, as you previously did with your wifi on / wifi off test. It is nothing to do with the CDN or any caching at my end, it's just the local device.

I did just that. Added a single word, then `Share current note`. Force hard refresh in Firefox for Android, no change.

I added the word "Forum". Here's the Obsidian view:
![image](https://github.com/alangrainger/obsidian-share/assets/33608083/12adc597-30e7-44c7-a347-24464ad2ffaf)

**Comment by FeralFlora** [comment]
Here's the android view after force refreshing about 15 min after upload, wifi is off: ![Screenshot_20231009-144437.png](https://github.com/alangrainger/obsidian-share/assets/33608083/b8024c15-91f0-4b46-b2a7-77b4ca0d9097)

**Comment by alangrainger** [comment]
This is what I see:

![image](https://github.com/alangrainger/obsidian-share/assets/16197738/fbecd211-7678-424f-b7d2-1cd60037f7ca)

I'm sorry, I don't think I can help you here. The file is clearly cleared from the CDN cache.

**Comment by FeralFlora** [comment]
> This is what I see:
> 
> ![image](https://user-images.githubusercontent.com/16197738/273592171-394c97f7-9d42-4336-90ca-4327a662b20d.png)
> 
> I'm sorry, I don't think I can help you here. The file is clearly cleared from the CDN/server cache.
> 
> I will note also that the caching rules haven't changed from the old server, other than changing from 30 days to 4 hours at your request.

This is very strange indeed. I doubled-checked that wifi _is_ off. Then, went to Firefox Android -> `Settings` -> `Delete browsing data` -> select `Cached images and files` -> press `Delete browsing data -> Navigate to `about:cache` -> Disk `list cached entries` and verify that it is empty. Open the Share note webpage. Refresh from the three dot menu.

This should ensure that it's not a router issue, and not a local cache issue.

**Comment by FeralFlora** [comment]
@alangrainger Does Share note rely on localhost somehow? I am self-hosting [Timetagger](https://github.com/almarklein/timetagger) locally ([details here](https://timetagger.app/articles/selfhost/)), and I think some interference between the two might be going on. When I fiddled with Timetagger, suddenly everything behaved as expected, and I could finally see an up-to-date version of the note.

The reason I checked this out was that [ping.eu](https://ping.eu/)'s DNS lookup tells me that the domain server for share.note.sx is my localhost???

![image](https://github.com/alangrainger/obsidian-share/assets/33608083/fb1b85a6-9edc-4f63-a6ca-07f3fd8c0d50)


On my localhost's default port, I have Timetagger running.

**Comment by alangrainger** [comment]
If you don't know what `localhost` is in the context of that screenshot, I respectfully request that you refrain from making any further comments on server or caching setup.

**Comment by FeralFlora** [comment]
> If you don't know what `localhost` is in the context of that screenshot, I respectfully request that you refrain from making any further comments on server or caching setup.

Sorry, I misunderstood how nslookup works, but now understand that you can specify which stub resolver to use, and that the default is the system's. 

Anyway, while this connection was probably moot, as I previously demonstrated [here](https://github.com/alangrainger/obsidian-share/issues/19#issuecomment-1752980063), the issue can not be written off as a router cache issue.

However, everything is mysteriously updating very quickly now, without even having to clear the browser cache, after I made changes to my Timetagger configuration (default port and logging in to the local user).

**Comment by alangrainger** [comment]
Heads-up, over the last hour I have migrated all shared files to a new file structure so that I can better target the right files and get the right caching result.

99% of files migrated correctly, but there may be some missing. 

As an example, this note migrated perfectly: https://share.note.sx/e612da498b038c3e5e367043782e2b59 , but if you notice anything missing simply share the note again.

You can see the headers are now `no-cache` for the note document:

![image](https://github.com/alangrainger/obsidian-share/assets/16197738/1d0acf66-6a71-41be-8ec7-f00e98ed6646)
