### ISSUE TITLE
Linked notes without frontmatter YAML fail

### ISSUE THREAD

**Issue by gapmiss** [alangrainger/obsidian-share#2]
fail:
- attempting to share `note 1`
- `note1` contains wiki-link to `note2`
- `note2` does NOT contain frontmatter YAML
- RESULT: TypeError: Cannot read properties of undefined (reading 'share_link')

success:
- attempting to share `note 1`
- `note1` contains wiki-link to `note2`
- `note2` contains frontmatter YAML
- RESULT: Success message → "File has been shared"

**Comment by alangrainger** [comment]
We'll move discussion to the forum thread so it can benefit all users. I believe this may be that Javascript on your device doesn't support "optional chaining". What device are you using?

Please let me know here: https://forum.obsidian.md/t/obsidian-share-publicly-share-notes-without-needing-a-full-digital-garden-supports-themes-images-callouts-and-more/42788

**Comment by alangrainger** [comment]
Thanks - resolved now, you can copy the updated code.

We'll move discussion for anything else to the forum thread so it can benefit all users: https://forum.obsidian.md/t/obsidian-share-publicly-share-notes-without-needing-a-full-digital-garden-supports-themes-images-callouts-and-more/42788
