### ISSUE TITLE
Neither inline title nor banner header present for note with banner

### ISSUE THREAD

**Issue by FeralFlora** [alangrainger/obsidian-share#20]
I cannot get either the banner header or the inline title (`Show inline title`) to appear in the uploaded note anymore. 

See this upload: https://share.note.sx/e612da498b038c3e5e367043782e2b59

In Obsidian, it has a banner header as you can see here:
![image](https://github.com/alangrainger/obsidian-share/assets/33608083/8baa5a6a-a26c-4251-b52c-f488d8bf6a59)

I've also tried to remove the header and enable Show inline title instead, but that doesn't appear either.

I've force re-uploaded the note and refreshed several times without cache.

Demo vault: 
[Share note demo vault.zip](https://github.com/alangrainger/obsidian-share/files/12840629/Share.note.demo.vault.zip)

**Comment by alangrainger** [comment]
Can reproduce some issues - will investigate and get back to you.

**Comment by alangrainger** [comment]
There was an issue on the server when trying to add the element `stype` instead of the element `style` 🤦‍♂️ 

Fixed now. Here's the note:

https://share.note.sx/5d4d9v65

**Comment by FeralFlora** [comment]
> Fixed now.

Nice, it looks great now!
