### ISSUE TITLE
Banner header overlaps subsequent content on mobile device

### ISSUE THREAD

**Issue by FeralFlora** [alangrainger/obsidian-share#21]
See the screenshot:

![Screenshot_20231008-223352.png](https://github.com/alangrainger/obsidian-share/assets/33608083/af7bc469-980f-4cb9-99c3-74a93f807464)

This is on an Android, using Firefox mobile.

The note link is https://share.note.sx/e612da498b038c3e5e367043782e2b59.

**Comment by alangrainger** [comment]
That's the theme, sorry to say. Here it is in your demo vault in mobile view. What we see on the web is an identical copy:

![image](https://github.com/alangrainger/obsidian-share/assets/16197738/3c723a48-6d64-4bff-9049-bd330b79cbc3)

If it looks different on your mobile device, make sure you have turned the properties OFF (hidden), the same as you are showing for the shared notes.

You can test the mobile view in Obsidian by opening up your Developer tools, and entering the command:

```
app.emulateMobile(true)
```

then just change the window size to mobile device size.

**Comment by alangrainger** [comment]
I would recommend using CSS snippets to fix the problem in the theme (using that emulate mobile trick), then your mobile shared notes will also be fixed.

**Comment by FeralFlora** [comment]
> That's the theme, sorry to say.

Oh, yeah, looks just as bad locally with mobile emulation. I will either make a css fix or just abandon the use of banner headers in favor of either the inline filename title, or a H1.
