### ISSUE TITLE
Callout icons are sometimes missing

### ISSUE THREAD

**Issue by FeralFlora** [alangrainger/obsidian-share#22]
Sometimes, actually quite often, the callouts are missing their icons in my case.

I'm not sure what the cause may be, since the same callout type sometimes has its icon present, sometimes not.

Here's some examples from [this note:](https://share.note.sx/e612da498b038c3e5e367043782e2b59)

![image](https://github.com/alangrainger/obsidian-share/assets/33608083/f751a251-12f2-48d3-872a-900abaf92a87)

![image](https://github.com/alangrainger/obsidian-share/assets/33608083/b2a27298-2a6e-4358-bf3f-297966493c7b)

Demo vault:
[callout-icon-demo-vault.zip](https://github.com/alangrainger/obsidian-share/files/12841796/callout-icon-demo-vault.zip)

**Comment by alangrainger** [comment]
This one will take quite some time, and an overhaul of how the note rendering works.

Based on my initial investigation, it appears that Obsidian only renders some elements _when they are in the viewport_. So to get a perfect copy of note content which is quite far down the page, I'll need to have the note window visually scroll down to each section, then take a snapshot of that section, then stitch them together, and _then_ upload.

Big task as you can imagine.

**Comment by alangrainger** [comment]
Hi @FeralFlora this should now be (mostly?) fixed in 0.5.17:

https://share.note.sx/slupasdq

https://share.note.sx/rpbhoabf

This was a tricky issue to reverse-engineer what Obsidian was doing here, and while it seems to be a successful solution, I can imagine there may be custom themes or custom CSS snippets which might cause the solution to fail.

**Comment by FeralFlora** [comment]
Not sure why, but one stubborn callout icon is missing (question callout):

![image](https://github.com/alangrainger/obsidian-share/assets/33608083/7a1a7a0e-09a0-4ec2-98c1-5cdffa5c324e)


There are icons below it that are not missing. See: https://share.note.sx/e612da498b038c3e5e367043782e2b59

**Comment by alangrainger** [comment]
Thanks - I can see the issue - some Lucide icon names are prefixed in the CSS with `lucide-` while some aren't. The Lucide icon software is expecting all icon names without a prefix. Will be fixed in the next release.

**Comment by alangrainger** [comment]
Question callout type (and others) fixed in 0.5.22.
