### ISSUE TITLE
Make the `copy` button functional in code blocks

### ISSUE THREAD

**Issue by FeralFlora** [alangrainger/obsidian-share#24]
In the guide I shared recently, I was sharing some code snippets in code blocks. 
As the visual elements are all present from Obsidian, there is a `copy` button in the code blocks. However, it is non-functional, which is a bit misleading, so I had to add a disclaimer about it.

It would be great if these buttons were functional, similar to how you made the callouts actually collapsible / expandable.

**Comment by alangrainger** [comment]
This is now functional. No update is needed for your notes - they will pick up the updated Javascript automatically.

If you don't see this functional at your end, again it is a caching issue at your end. 

If you want to force the cache to update, visit this URL and refresh it until you see a `Copy code button` section: https://share.note.sx/.assets/app.js

**Comment by FeralFlora** [comment]
> If you don't see this functional at your end, again it is a caching issue at your end.

I do see it, thanks! It works great 👍
