### ISSUE TITLE
Add ability to set webpage title in properties, or use first H1 heading / banner header as webpage title

### ISSUE THREAD

**Issue by FeralFlora** [alangrainger/obsidian-share#25]
In this note: https://share.note.sx/e612da498b038c3e5e367043782e2b59, I have an H1 heading, which I regard as the title of the article / document, namely "Kanban Reading List for Academics".

However, when I share the link, the link preview shows the HTML title, which is the same as the local filename in Obsidian.
![image](https://github.com/alangrainger/obsidian-share/assets/33608083/cd439e3d-e2f5-478e-8f0c-46068ed5b64e)

Given a H1 title or banner header in the note / document, it would be nice if these were used as the HTML title (shown in the title bar). In the absence of these, the filename could be used as a fallback option. For more user control, and less ambiguity, this could also be set in a `share_title` property.

**Comment by alangrainger** [comment]
Great suggestion! Done in 0.5.9.
