### ISSUE TITLE
Error uploading current note

### ISSUE THREAD

**Issue by swehba** [alangrainger/obsidian-share#28]
1. Installed the plugin.
2. Obtained an API key.
3. Went to one of my notes and selected "Share Note: Share current note" from the command palette.
4. An error message was displayed saying "There was an error uploading the note. Please try again."
5. Trying again results in the same error.

**Comment by alangrainger** [comment]
I've just made a couple of new test vaults with new accounts this morning and I can't replicate the error.

Could you please open the Sandbox vault, install the plugin, and check if you still see the error?

**Comment by alangrainger** [comment]
I can see there was a problem earlier today with some error messages not showing - so if you try now it might give more information which will help solve it the issue.

**Comment by MelodyDuplaix** [comment]
I have the same problem since today, even with the sandbox vault. 
I have this in the console:
![image](https://github.com/alangrainger/obsidian-share/assets/131142776/c1f12a2f-c06c-4021-b946-437fb2dae35f)

**Comment by MelodyDuplaix** [comment]
I can replicate the issue with this simply vault:
[test.zip](https://github.com/alangrainger/obsidian-share/files/12909825/test.zip)

**Comment by alangrainger** [comment]
Sorry @MelodyDuplaix , that was my fault - I accidentally turned off the content-type header on the server today. It doesn't explain @swehba 's issue as this was only around 10 hours ago.

Sorry about the unplanned outage! All working again.

**Comment by alangrainger** [comment]
And thank you for messaging @MelodyDuplaix - otherwise it would have been a longer outage. Much appreciated! ❤️

**Comment by MelodyDuplaix** [comment]
Thanks to you for the plugin! @alangrainger
