### ISSUE TITLE
Large notes fail to share

### ISSUE THREAD

**Issue by TheColorman** [alangrainger/obsidian-share#5]
Sharing a note, I get "Unable to find the file to update, please delete any existing share links and try again", or a 403 response. I used to use the old version of the plugin through templater, so I thought it might be due to the old share links, but removing them did not help.

That means it's probably an authentication issue. My user ID is `efc89ed13177ef9c8c77729abc03b3cc`.

**Fix for "Unable to find the file to update":** go to [this comment](https://github.com/alangrainger/obsidian-share/issues/5#issuecomment-1718163077).
"Large notes fail" starts after that.

**Comment by alangrainger** [comment]
That's very strange - if you've deleted the share link from the note it should create a brand new random one.

That being said you're the first person trying the plugin who is coming from the old Templater version (thank you by the way!) so we might need to do a bit of troubleshooting.
The 403 error comes if you try and update a note owned by another user - for example if you grab one of my public URLs and try and overwrite is.

If you create a brand new note and share it, does it work?

**Comment by TheColorman** [comment]
Nope, tried to create an entirely new note for troubleshooting, same error. Tried creating a new vault and it works just fine there (on related note, is there a way to delete notes after uploading? Wouldn't want to fill you storage with junk).

**Comment by TheColorman** [comment]
I copied over the `.obsidian` folder to thew new vault and it stopped working. Might be one of my old plugins, I'll keep looking.

**Comment by TheColorman** [comment]
Whatever the problem was, it was resolved by replacing my version of the Share plugin with one installed in a completely new vault.
Mismatch between new uid/old api key or old apikey and new uid?

**Comment by alangrainger** [comment]
Excellent! I was halfway through adding detailed debug logging so I could figure out what was going wrong, but I'm glad that it's solved, and the logging will be useful anyway.

All good to close the issue? 

Also I'd be keen for any feedback or suggestions for improvement 👍

**Comment by TheColorman** [comment]
Ok now this is *really* weird.
I have my main vault, Main. I created vault A, and copied `.obsidian` from Main to A. Upload did not work. I uninstalled and reinstalled the plugin. Upload did not work.
I then cerated a new vault B, installed the plugin (this time without copying my `.obsidian`) and sharing worked. I copied the plugin folder to vault A, sharing worked.

Then I copied it to vault Main, did not work. Then I re-created vault B and copied from B to Main and it still did not work.

Sorry, looks like I might be needing the debugger after all unless I figure out what happened😅

**Comment by alangrainger** [comment]
Ok - logging is added, so give it a go and hopefully I can figure out what's going wrong.

**Comment by TheColorman** [comment]
Okay doesn't look like it's failing uploads anymore:
- A with Main .obsidian.
- Clean B with installed Share plugin.
1. Authenticated with B. Copied plugin to A. A could not share. 
2. Recreated API key with A. A could not share.
3. Tried sharing with B. Wrong API key (as expected), recreated API key. B could share.
4. Tried sharing with A. Wrong API key, recreated. A could now share.

Same procedure with my main vault worked this time. *Very* confured about why it has worked / not worked on specific tries.

A new issue has risen though, now when sharing, the scrips gets stuck at [this line](https://github.com/alangrainger/obsidian-share/blob/3598606257bf374cb481c87fba1cd538ede3f7d6/src/crypto.ts#L74).
What can I do to debug this on my end?

**Comment by alangrainger** [comment]
Thanks for sharing that - I can replicate the issue so I will debug and solve.  Looks like it might be related to the size of the note itself. I can cause the same failure with 20,000 words of Lorem Ipsum.

No idea regarding the A/B failures 😬 If it does reoccur, we might be able to diagnose now.

**Comment by TheColorman** [comment]
As for feedback, first I'd like to thank you for creating such an awesome plugin! Very useful to be able to share notes you've written with others!

As for feedback, the biggest right now is probably math. It doesn't render for me at all on the shared link (I noticed that the MathJax DOM elements contain no inner html, but that's probably a problem for a different issue.)
Features that could be awesome down the line would be some way to crawl-share notes. So you would share a note, and it would recursively share all linked notes (maybe with a directory/tag blacklister in settings to prevent sensitive notes from being shared).

**Comment by alangrainger** [comment]
@TheColorman this long note encryption is fixed in 0.2.6.

For your math-heavy note, the method I'm using to get the HTML data from Obsidian seems to have intermittent failures. I think I will need to page through each of the Obsidian viewport views and piece them together that way. I will leave this ticket open.

**Comment by alangrainger** [comment]
@TheColorman I can save you the effort of writing a message - I can see from the logs you have the 403 again, and better yet, I can see the exact issue!

Making a fix now, should be live very shortly.

**Comment by TheColorman** [comment]
Only happened when I tried to force upload, since normal upload worked fine I decided it wasn't important enough to write in about 😅

**Comment by alangrainger** [comment]
Here's the offending line. Fixed now in 0.2.7.

https://github.com/alangrainger/obsidian-share/commit/82be12c215bdb0849d7249e4d1a98e6808be54cd#diff-d6198cff69fcf66b5a1c2b4d4f8e2101a5e9c64dc24bae1a904d49abc2ae4f0cL237-R237

**Comment by alangrainger** [comment]
@TheColorman MathJax / LaTeX support is now added in 0.3.2.

You will likely need to `Force re-upload` one of your notes which includes MathJax to get it to start working, as this will inject the needed styles into your public CSS and purge the cache. Once you've done that the rest of your notes should start working without issues.
