### ISSUE TITLE
FR: svg image support

### ISSUE THREAD

**Issue by MelodyDuplaix** [alangrainger/obsidian-share#6]
This plugin can be super useful. I used to use it as a template. But with the plugin , apparently it's not possible to publish a note containing an svg image. Is it because it's more complicated to implement or too heavy to host? If not, would it be possible to implement it?

**Comment by alangrainger** [comment]
> Is it because it's more complicated

Not at all, I just have a whitelist of allowed types to make things safe. SVG is now added, so share away! 😊

[Example shared note with SVG](https://file.obsidianshare.com/14/66b31eb229208ef5134314feced15c6b.html#VUuNXrm8GvbdrpaVPvhfXNiDLM2YQ81Y0fQzRVNrmhU)
