### ISSUE TITLE
Can't decrypt a previously encrypted note

### ISSUE THREAD

**Issue by FeralFlora** [alangrainger/obsidian-share#7]
First of all, thank you for this truly amazing plugin!

I'm trying out the new `share_unencrypted: true` property option, because I want a preview of the note to appear when sharing the link. The note was previously shared / uploaded without this property, so it was encrypted.

Is it possible to have `share_unencrypted: true` decrypt a previously encrypted upload. If not, what might a workaround be? A related question, is it possible to remove / unshare a shared note?

**Comment by FeralFlora** [comment]
I made a mistake and hadn't set the property type to checkbox. Now that I did, and shared the note again, I do actually get a link without an encryption key: "https://file.obsidianshare.com/70/e612da498b038c3e5e367043782e2b59.html"

However, the note is still encrypted, so this just makes the link non-functional:
![image](https://github.com/alangrainger/obsidian-share/assets/33608083/2e1ac6c6-7feb-46d8-aec5-40ff19a3ec55)

**Comment by FeralFlora** [comment]
Okay, nevermind. After waiting a while, and reloading the link above, the note is not encrypted anymore! So either it just takes a while to decrypt, or I was seeing a cached version.

**Comment by alangrainger** [comment]
All good :)

You don't even need to wait a while, just refresh your browser. 

The cache is immediately cleared at the server end when you re-upload a note, so you just need to refresh a couple of times at your end.
