### ISSUE TITLE
[FR] Better support for Banners

### ISSUE THREAD

**Issue by FeralFlora** [alangrainger/obsidian-share#8]
I tried adding a banner to a shared note, but the banner only appears as a small image at the top, rather than going the full width as in the original note. Also, if I add a banner header, its placement is not right, and it overlaps the text in the main document.

Online:
![image](https://github.com/alangrainger/obsidian-share/assets/33608083/e9987064-962e-420a-a9a7-2801b2bb802e)

Offline:
![image](https://github.com/alangrainger/obsidian-share/assets/33608083/90235041-eb73-4b16-931b-53b35b86cceb)

Also, as you can see, the offline banner has a gradient, but the online one doesn't.

**Comment by alangrainger** [comment]
Can you please provide a list of the plugins and themes needed to make the view you want?

**Comment by FeralFlora** [comment]
> Can you please upload a demo vault configured with some demo notes and the plugins and themes needed to get the view you want. Otherwise I won't be able to replicate what you need.

Yes, I could do that later. But basically, I just want the banner displayed similarly to what you can see in the "offline" document inside Obsidian. Share note manages to replicate everything else very well, but the banner doesn't display the same way.

> Can you explain what you mean by "offline" and "online"? The online version looks like the correct one based on your screenshots.

The online version is the hosted version by Share note. The offline version is my local note in Obsidian.

A banner is meant to span full width at the top of the note. See other examples here: https://github.com/noatpad/obsidian-banners

**Comment by alangrainger** [comment]
Thanks - I'll leave it with you to create the sample vault to test with. Just upload it in this thread as a zipfile.

**Comment by FeralFlora** [comment]
Hey @alangrainger, here's the demo vault: 
[Share note demo vault.zip](https://github.com/alangrainger/obsidian-share/files/12693448/Share.note.demo.vault.zip)

**Comment by alangrainger** [comment]
This is fixed in 0.3.3:

https://file.obsidianshare.com/db/2fc09e99eb72414c2550dbb5cf92543e.html
