### ISSUE TITLE
[BUG] Link indicators are missing

### ISSUE THREAD

**Issue by FeralFlora** [alangrainger/obsidian-share#9]
Link indicators seem to missing, leaving instead a blank space.

In Obsidian:
![image](https://github.com/alangrainger/obsidian-share/assets/33608083/f49b434d-0c33-47c4-8efd-f6ef54c75563)

Online:
![image](https://github.com/alangrainger/obsidian-share/assets/33608083/51bf4283-975b-4517-94c0-1b6a46aa60e4)

**Comment by alangrainger** [comment]
I'm not sure where those come from sorry. If you can figure it out please post here.

**Comment by alangrainger** [comment]
No, I mean how they get inserted into the DOM. I can't find the CSS or Javascript that adds them.

**Comment by FeralFlora** [comment]
The SVG is called: `874d8b8e340f75575caa.svg`.

And the element is
```
<img class="cm-widgetBuffer" aria-hidden="true">
```
![image](https://github.com/alangrainger/obsidian-share/assets/33608083/09ecf7f2-b602-4e06-9743-4118c6d9ec9c)

![image](https://github.com/alangrainger/obsidian-share/assets/33608083/fd435c04-0fd8-4360-bc5f-f310cea83380)

**Comment by alangrainger** [comment]
Many thanks, but it's the one in the Preview/Reading mode that we need to find:

![image](https://github.com/alangrainger/obsidian-share/assets/16197738/6f47f19a-c26e-46fb-a09a-03b0482c00ab)

**Comment by alangrainger** [comment]
Actually you did already sort of answer the question - it is indeed `874d8b8e340f75575caa.svg`

More specifically `public/images/874d8b8e340f75575caa.svg`. I will have to see how that can be extracted and re-uploaded.

**Comment by alangrainger** [comment]
This is fixed in 0.3.6, thanks for your assistance 👍

**Comment by FeralFlora** [comment]
> This is fixed in 0.3.6, thanks for your assistance 👍
> You will need to force re-upload your theme after upgrading.

Great, thanks likewise!

**Comment by FeralFlora** [comment]
@alangrainger Just tested this, and it doesn't seem to be working for me:
![image](https://github.com/alangrainger/obsidian-share/assets/33608083/c8f1fd5f-6efc-4458-bfe9-c40420d333cf)
![image](https://github.com/alangrainger/obsidian-share/assets/33608083/168391f5-844a-41b1-b1a2-7d9d1b44ef37)


This is after forcing a re-upload.

**Comment by alangrainger** [comment]
Ok try again:

https://file.obsidianshare.com/db/2fc09e99eb72414c2550dbb5cf92543e.html

**Comment by FeralFlora** [comment]
I will try later tonight

**Comment by FeralFlora** [comment]
> Ok update to 0.3.8 and try again:
> 
> https://file.obsidianshare.com/db/2fc09e99eb72414c2550dbb5cf92543e.html

Yup, that fixed it - thanks! 👍
